-- Data acuan modul PROYEK — dihasilkan oleh scripts/acuan-sql.mjs.
-- JANGAN disunting tangan: sumbernya prisma/acuan/*.json.
--
-- Dijalankan SESUDAH prisma/proyek.sql, sekali, sebelum tim mulai mengisi.
-- Aman dijalankan ulang: tiap baris punya id tetap dan diakhiri
-- "on conflict do nothing", jadi menjalankan dua kali tidak menggandakan
-- apa pun dan juga TIDAK menimpa nilai yang sudah disunting tim.
--
-- Urutan pengisian data sesudah ini: docs/urutan-isi-data.md

begin;

-- 183 baris hak akses (12 sub-bagian × peran yang boleh melihat).
-- Baris ADA berarti boleh melihat; "bolehUbah" menentukan boleh mengubah.
-- Sub-bagian yang tidak tercantum untuk sebuah peran tertutup sama sekali.
insert into proyek.role_section_permissions ("id", "roleNama", "section", "bolehUbah") values
  ('rsp-administrator-sistem-deskripsi', 'Administrator Sistem', 'deskripsi', true),
  ('rsp-komisaris-deskripsi', 'Komisaris', 'deskripsi', false),
  ('rsp-bod-deskripsi', 'BOD', 'deskripsi', true),
  ('rsp-head-operation-office-deskripsi', 'Head Operation Office', 'deskripsi', true),
  ('rsp-head-operation-project-deskripsi', 'Head Operation Project', 'deskripsi', false),
  ('rsp-project-manager-deskripsi', 'Project Manager', 'deskripsi', false),
  ('rsp-supervisor-deskripsi', 'Supervisor', 'deskripsi', false),
  ('rsp-business-development-deskripsi', 'Business Development', 'deskripsi', true),
  ('rsp-arsitek-deskripsi', 'Arsitek', 'deskripsi', false),
  ('rsp-quantity-surveyor-deskripsi', 'Quantity Surveyor', 'deskripsi', false),
  ('rsp-procurement-deskripsi', 'Procurement', 'deskripsi', false),
  ('rsp-customer-care-deskripsi', 'Customer Care', 'deskripsi', false),
  ('rsp-consultant-finance-deskripsi', 'Consultant Finance', 'deskripsi', false),
  ('rsp-finance-deskripsi', 'Finance', 'deskripsi', false),
  ('rsp-admin-deskripsi', 'Admin', 'deskripsi', false),
  ('rsp-hrd-deskripsi', 'HRD', 'deskripsi', false),
  ('rsp-head-marketing-sales-deskripsi', 'Head Marketing & Sales', 'deskripsi', false),
  ('rsp-agent-coordinator-deskripsi', 'Agent Coordinator', 'deskripsi', false),
  ('rsp-sales-deskripsi', 'Sales', 'deskripsi', false),
  ('rsp-head-content-media-deskripsi', 'Head Content & Media', 'deskripsi', false),
  ('rsp-editor-deskripsi', 'Editor', 'deskripsi', false),
  ('rsp-social-media-deskripsi', 'Social Media', 'deskripsi', false),
  ('rsp-administrator-sistem-daftarunit', 'Administrator Sistem', 'daftarUnit', true),
  ('rsp-komisaris-daftarunit', 'Komisaris', 'daftarUnit', false),
  ('rsp-bod-daftarunit', 'BOD', 'daftarUnit', true),
  ('rsp-head-operation-office-daftarunit', 'Head Operation Office', 'daftarUnit', true),
  ('rsp-head-operation-project-daftarunit', 'Head Operation Project', 'daftarUnit', true),
  ('rsp-project-manager-daftarunit', 'Project Manager', 'daftarUnit', true),
  ('rsp-supervisor-daftarunit', 'Supervisor', 'daftarUnit', false),
  ('rsp-business-development-daftarunit', 'Business Development', 'daftarUnit', false),
  ('rsp-arsitek-daftarunit', 'Arsitek', 'daftarUnit', false),
  ('rsp-quantity-surveyor-daftarunit', 'Quantity Surveyor', 'daftarUnit', false),
  ('rsp-procurement-daftarunit', 'Procurement', 'daftarUnit', false),
  ('rsp-customer-care-daftarunit', 'Customer Care', 'daftarUnit', false),
  ('rsp-consultant-finance-daftarunit', 'Consultant Finance', 'daftarUnit', false),
  ('rsp-finance-daftarunit', 'Finance', 'daftarUnit', false),
  ('rsp-admin-daftarunit', 'Admin', 'daftarUnit', false),
  ('rsp-hrd-daftarunit', 'HRD', 'daftarUnit', false),
  ('rsp-head-marketing-sales-daftarunit', 'Head Marketing & Sales', 'daftarUnit', false),
  ('rsp-agent-coordinator-daftarunit', 'Agent Coordinator', 'daftarUnit', false),
  ('rsp-sales-daftarunit', 'Sales', 'daftarUnit', false),
  ('rsp-head-content-media-daftarunit', 'Head Content & Media', 'daftarUnit', false),
  ('rsp-editor-daftarunit', 'Editor', 'daftarUnit', false),
  ('rsp-social-media-daftarunit', 'Social Media', 'daftarUnit', false),
  ('rsp-administrator-sistem-daftarsarpras', 'Administrator Sistem', 'daftarSarpras', true),
  ('rsp-komisaris-daftarsarpras', 'Komisaris', 'daftarSarpras', false),
  ('rsp-bod-daftarsarpras', 'BOD', 'daftarSarpras', true),
  ('rsp-head-operation-office-daftarsarpras', 'Head Operation Office', 'daftarSarpras', true),
  ('rsp-head-operation-project-daftarsarpras', 'Head Operation Project', 'daftarSarpras', true),
  ('rsp-project-manager-daftarsarpras', 'Project Manager', 'daftarSarpras', true),
  ('rsp-supervisor-daftarsarpras', 'Supervisor', 'daftarSarpras', false),
  ('rsp-business-development-daftarsarpras', 'Business Development', 'daftarSarpras', false),
  ('rsp-arsitek-daftarsarpras', 'Arsitek', 'daftarSarpras', false),
  ('rsp-quantity-surveyor-daftarsarpras', 'Quantity Surveyor', 'daftarSarpras', false),
  ('rsp-procurement-daftarsarpras', 'Procurement', 'daftarSarpras', false),
  ('rsp-customer-care-daftarsarpras', 'Customer Care', 'daftarSarpras', false),
  ('rsp-consultant-finance-daftarsarpras', 'Consultant Finance', 'daftarSarpras', false),
  ('rsp-finance-daftarsarpras', 'Finance', 'daftarSarpras', false),
  ('rsp-admin-daftarsarpras', 'Admin', 'daftarSarpras', false),
  ('rsp-hrd-daftarsarpras', 'HRD', 'daftarSarpras', false),
  ('rsp-head-marketing-sales-daftarsarpras', 'Head Marketing & Sales', 'daftarSarpras', false),
  ('rsp-agent-coordinator-daftarsarpras', 'Agent Coordinator', 'daftarSarpras', false),
  ('rsp-sales-daftarsarpras', 'Sales', 'daftarSarpras', false),
  ('rsp-head-content-media-daftarsarpras', 'Head Content & Media', 'daftarSarpras', false),
  ('rsp-editor-daftarsarpras', 'Editor', 'daftarSarpras', false),
  ('rsp-social-media-daftarsarpras', 'Social Media', 'daftarSarpras', false),
  ('rsp-administrator-sistem-dokumenteknis', 'Administrator Sistem', 'dokumenTeknis', true),
  ('rsp-komisaris-dokumenteknis', 'Komisaris', 'dokumenTeknis', false),
  ('rsp-bod-dokumenteknis', 'BOD', 'dokumenTeknis', true),
  ('rsp-head-operation-office-dokumenteknis', 'Head Operation Office', 'dokumenTeknis', false),
  ('rsp-head-operation-project-dokumenteknis', 'Head Operation Project', 'dokumenTeknis', true),
  ('rsp-project-manager-dokumenteknis', 'Project Manager', 'dokumenTeknis', true),
  ('rsp-supervisor-dokumenteknis', 'Supervisor', 'dokumenTeknis', false),
  ('rsp-business-development-dokumenteknis', 'Business Development', 'dokumenTeknis', false),
  ('rsp-arsitek-dokumenteknis', 'Arsitek', 'dokumenTeknis', true),
  ('rsp-quantity-surveyor-dokumenteknis', 'Quantity Surveyor', 'dokumenTeknis', false),
  ('rsp-procurement-dokumenteknis', 'Procurement', 'dokumenTeknis', false),
  ('rsp-customer-care-dokumenteknis', 'Customer Care', 'dokumenTeknis', false),
  ('rsp-consultant-finance-dokumenteknis', 'Consultant Finance', 'dokumenTeknis', false),
  ('rsp-finance-dokumenteknis', 'Finance', 'dokumenTeknis', false),
  ('rsp-admin-dokumenteknis', 'Admin', 'dokumenTeknis', false),
  ('rsp-hrd-dokumenteknis', 'HRD', 'dokumenTeknis', false),
  ('rsp-head-marketing-sales-dokumenteknis', 'Head Marketing & Sales', 'dokumenTeknis', false),
  ('rsp-agent-coordinator-dokumenteknis', 'Agent Coordinator', 'dokumenTeknis', false),
  ('rsp-sales-dokumenteknis', 'Sales', 'dokumenTeknis', false),
  ('rsp-head-content-media-dokumenteknis', 'Head Content & Media', 'dokumenTeknis', false),
  ('rsp-editor-dokumenteknis', 'Editor', 'dokumenTeknis', false),
  ('rsp-social-media-dokumenteknis', 'Social Media', 'dokumenTeknis', false),
  ('rsp-administrator-sistem-hargarabrap', 'Administrator Sistem', 'hargaRabRap', true),
  ('rsp-komisaris-hargarabrap', 'Komisaris', 'hargaRabRap', false),
  ('rsp-bod-hargarabrap', 'BOD', 'hargaRabRap', true),
  ('rsp-business-development-hargarabrap', 'Business Development', 'hargaRabRap', false),
  ('rsp-head-operation-office-hargarabrap', 'Head Operation Office', 'hargaRabRap', true),
  ('rsp-head-operation-project-hargarabrap', 'Head Operation Project', 'hargaRabRap', false),
  ('rsp-project-manager-hargarabrap', 'Project Manager', 'hargaRabRap', false),
  ('rsp-quantity-surveyor-hargarabrap', 'Quantity Surveyor', 'hargaRabRap', true),
  ('rsp-procurement-hargarabrap', 'Procurement', 'hargaRabRap', false),
  ('rsp-admin-hargarabrap', 'Admin', 'hargaRabRap', false),
  ('rsp-finance-hargarabrap', 'Finance', 'hargaRabRap', false),
  ('rsp-consultant-finance-hargarabrap', 'Consultant Finance', 'hargaRabRap', false),
  ('rsp-administrator-sistem-setujuirab', 'Administrator Sistem', 'setujuiRab', true),
  ('rsp-komisaris-setujuirab', 'Komisaris', 'setujuiRab', false),
  ('rsp-bod-setujuirab', 'BOD', 'setujuiRab', true),
  ('rsp-head-operation-office-setujuirab', 'Head Operation Office', 'setujuiRab', true),
  ('rsp-head-operation-project-setujuirab', 'Head Operation Project', 'setujuiRab', true),
  ('rsp-project-manager-setujuirab', 'Project Manager', 'setujuiRab', true),
  ('rsp-quantity-surveyor-setujuirab', 'Quantity Surveyor', 'setujuiRab', false),
  ('rsp-administrator-sistem-businessplan', 'Administrator Sistem', 'businessPlan', true),
  ('rsp-komisaris-businessplan', 'Komisaris', 'businessPlan', false),
  ('rsp-bod-businessplan', 'BOD', 'businessPlan', true),
  ('rsp-business-development-businessplan', 'Business Development', 'businessPlan', true),
  ('rsp-administrator-sistem-keuangan', 'Administrator Sistem', 'keuangan', true),
  ('rsp-bod-keuangan', 'BOD', 'keuangan', true),
  ('rsp-business-development-keuangan', 'Business Development', 'keuangan', false),
  ('rsp-head-operation-office-keuangan', 'Head Operation Office', 'keuangan', true),
  ('rsp-head-operation-project-keuangan', 'Head Operation Project', 'keuangan', false),
  ('rsp-project-manager-keuangan', 'Project Manager', 'keuangan', false),
  ('rsp-quantity-surveyor-keuangan', 'Quantity Surveyor', 'keuangan', false),
  ('rsp-admin-keuangan', 'Admin', 'keuangan', true),
  ('rsp-finance-keuangan', 'Finance', 'keuangan', true),
  ('rsp-consultant-finance-keuangan', 'Consultant Finance', 'keuangan', false),
  ('rsp-administrator-sistem-pettycash', 'Administrator Sistem', 'pettyCash', true),
  ('rsp-bod-pettycash', 'BOD', 'pettyCash', true),
  ('rsp-head-operation-office-pettycash', 'Head Operation Office', 'pettyCash', false),
  ('rsp-head-operation-project-pettycash', 'Head Operation Project', 'pettyCash', true),
  ('rsp-project-manager-pettycash', 'Project Manager', 'pettyCash', false),
  ('rsp-supervisor-pettycash', 'Supervisor', 'pettyCash', true),
  ('rsp-quantity-surveyor-pettycash', 'Quantity Surveyor', 'pettyCash', true),
  ('rsp-admin-pettycash', 'Admin', 'pettyCash', true),
  ('rsp-finance-pettycash', 'Finance', 'pettyCash', true),
  ('rsp-consultant-finance-pettycash', 'Consultant Finance', 'pettyCash', true),
  ('rsp-administrator-sistem-progress', 'Administrator Sistem', 'progress', true),
  ('rsp-bod-progress', 'BOD', 'progress', true),
  ('rsp-head-operation-project-progress', 'Head Operation Project', 'progress', true),
  ('rsp-project-manager-progress', 'Project Manager', 'progress', true),
  ('rsp-supervisor-progress', 'Supervisor', 'progress', true),
  ('rsp-quantity-surveyor-progress', 'Quantity Surveyor', 'progress', true),
  ('rsp-arsitek-progress', 'Arsitek', 'progress', false),
  ('rsp-procurement-progress', 'Procurement', 'progress', false),
  ('rsp-administrator-sistem-aset', 'Administrator Sistem', 'aset', true),
  ('rsp-komisaris-aset', 'Komisaris', 'aset', false),
  ('rsp-bod-aset', 'BOD', 'aset', true),
  ('rsp-head-operation-office-aset', 'Head Operation Office', 'aset', true),
  ('rsp-head-operation-project-aset', 'Head Operation Project', 'aset', true),
  ('rsp-project-manager-aset', 'Project Manager', 'aset', true),
  ('rsp-supervisor-aset', 'Supervisor', 'aset', false),
  ('rsp-business-development-aset', 'Business Development', 'aset', false),
  ('rsp-arsitek-aset', 'Arsitek', 'aset', false),
  ('rsp-quantity-surveyor-aset', 'Quantity Surveyor', 'aset', false),
  ('rsp-procurement-aset', 'Procurement', 'aset', true),
  ('rsp-customer-care-aset', 'Customer Care', 'aset', false),
  ('rsp-consultant-finance-aset', 'Consultant Finance', 'aset', false),
  ('rsp-finance-aset', 'Finance', 'aset', false),
  ('rsp-admin-aset', 'Admin', 'aset', false),
  ('rsp-hrd-aset', 'HRD', 'aset', false),
  ('rsp-head-marketing-sales-aset', 'Head Marketing & Sales', 'aset', false),
  ('rsp-agent-coordinator-aset', 'Agent Coordinator', 'aset', false),
  ('rsp-sales-aset', 'Sales', 'aset', false),
  ('rsp-head-content-media-aset', 'Head Content & Media', 'aset', false),
  ('rsp-editor-aset', 'Editor', 'aset', false),
  ('rsp-social-media-aset', 'Social Media', 'aset', false),
  ('rsp-administrator-sistem-penyesuaianaset', 'Administrator Sistem', 'penyesuaianAset', true),
  ('rsp-komisaris-penyesuaianaset', 'Komisaris', 'penyesuaianAset', false),
  ('rsp-bod-penyesuaianaset', 'BOD', 'penyesuaianAset', true),
  ('rsp-head-operation-office-penyesuaianaset', 'Head Operation Office', 'penyesuaianAset', false),
  ('rsp-head-operation-project-penyesuaianaset', 'Head Operation Project', 'penyesuaianAset', true),
  ('rsp-project-manager-penyesuaianaset', 'Project Manager', 'penyesuaianAset', true),
  ('rsp-supervisor-penyesuaianaset', 'Supervisor', 'penyesuaianAset', true),
  ('rsp-business-development-penyesuaianaset', 'Business Development', 'penyesuaianAset', false),
  ('rsp-arsitek-penyesuaianaset', 'Arsitek', 'penyesuaianAset', false),
  ('rsp-quantity-surveyor-penyesuaianaset', 'Quantity Surveyor', 'penyesuaianAset', true),
  ('rsp-procurement-penyesuaianaset', 'Procurement', 'penyesuaianAset', false),
  ('rsp-customer-care-penyesuaianaset', 'Customer Care', 'penyesuaianAset', false),
  ('rsp-consultant-finance-penyesuaianaset', 'Consultant Finance', 'penyesuaianAset', false),
  ('rsp-finance-penyesuaianaset', 'Finance', 'penyesuaianAset', false),
  ('rsp-admin-penyesuaianaset', 'Admin', 'penyesuaianAset', false),
  ('rsp-hrd-penyesuaianaset', 'HRD', 'penyesuaianAset', false),
  ('rsp-head-marketing-sales-penyesuaianaset', 'Head Marketing & Sales', 'penyesuaianAset', false),
  ('rsp-agent-coordinator-penyesuaianaset', 'Agent Coordinator', 'penyesuaianAset', false),
  ('rsp-sales-penyesuaianaset', 'Sales', 'penyesuaianAset', false),
  ('rsp-head-content-media-penyesuaianaset', 'Head Content & Media', 'penyesuaianAset', false),
  ('rsp-editor-penyesuaianaset', 'Editor', 'penyesuaianAset', false),
  ('rsp-social-media-penyesuaianaset', 'Social Media', 'penyesuaianAset', false)
on conflict ("id") do nothing;

-- 22 harga dasar. Nilainya harga awal yang WAJIB disesuaikan
-- tim sebelum dipakai menyusun RAB — yang acuan di sini strukturnya, bukan angkanya.
insert into proyek.harga_dasar ("id", "kode", "kategori", "uraian", "satuan", "hargaAcuan") values
  ('hd-l-01', 'L.01', 'UPAH', 'Pekerja', 'OH', 110000),
  ('hd-l-02', 'L.02', 'UPAH', 'Tukang batu', 'OH', 150000),
  ('hd-l-03', 'L.03', 'UPAH', 'Tukang kayu', 'OH', 150000),
  ('hd-l-05', 'L.05', 'UPAH', 'Kepala tukang', 'OH', 170000),
  ('hd-l-06', 'L.06', 'UPAH', 'Mandor', 'OH', 180000),
  ('hd-m-01', 'M.01', 'BAHAN', 'Semen Portland (PC)', 'kg', 1600),
  ('hd-m-02', 'M.02', 'BAHAN', 'Pasir pasang', 'm3', 250000),
  ('hd-m-03', 'M.03', 'BAHAN', 'Pasir beton (cor)', 'm3', 300000),
  ('hd-m-04', 'M.04', 'BAHAN', 'Batu belah/kali 15/20', 'm3', 350000),
  ('hd-m-05', 'M.05', 'BAHAN', 'Kerikil/split beton', 'm3', 400000),
  ('hd-m-06', 'M.06', 'BAHAN', 'Besi beton polos', 'kg', 15000),
  ('hd-m-07', 'M.07', 'BAHAN', 'Kawat beton (bendrat)', 'kg', 25000),
  ('hd-m-08', 'M.08', 'BAHAN', 'Kayu bekisting/papan', 'm3', 3500000),
  ('hd-m-09', 'M.09', 'BAHAN', 'Paku 5–10 cm', 'kg', 22000),
  ('hd-m-10', 'M.10', 'BAHAN', 'Bata ringan (hebel)', 'm3', 650000),
  ('hd-m-11', 'M.11', 'BAHAN', 'Semen instan (mortar)', 'sak', 62000),
  ('hd-m-12', 'M.12', 'BAHAN', 'Keramik lantai 40×40', 'm2', 65000),
  ('hd-m-13', 'M.13', 'BAHAN', 'Cat tembok interior', 'kg', 35000),
  ('hd-m-14', 'M.14', 'BAHAN', 'Pipa PVC AW 1/2"', 'btg', 45000),
  ('hd-m-15', 'M.15', 'BAHAN', 'Kabel NYM 3×2,5', 'm', 22000),
  ('hd-m-16', 'M.16', 'BAHAN', 'Saklar/stopkontak + aksesoris', 'titik', 45000),
  ('hd-e-01', 'E.01', 'ALAT', 'Sewa concrete mixer (molen)', 'hari', 350000)
on conflict ("id") do nothing;

-- 12 analisa harga satuan, koefisien bergaya SNI AHSP.
-- Harga satuannya TIDAK disimpan: selalu dihitung dari komponen × harga dasar.
insert into proyek.analisa_harga ("id", "kode", "uraian", "satuan", "kelompok", "overheadPct") values
  ('an-a-01', 'A.01', 'Pembersihan lapangan & perataan', 'm2', 'Pekerjaan Persiapan', 13),
  ('an-a-02', 'A.02', 'Pengukuran & pemasangan bouwplank', 'm''', 'Pekerjaan Persiapan', 13),
  ('an-a-03', 'A.03', 'Galian tanah biasa sedalam ≤ 1 m', 'm3', 'Pekerjaan Tanah', 13),
  ('an-a-04', 'A.04', 'Urugan kembali & pemadatan', 'm3', 'Pekerjaan Tanah', 13),
  ('an-a-05', 'A.05', 'Pasangan pondasi batu kali camp. 1:4', 'm3', 'Pekerjaan Struktur', 13),
  ('an-a-06', 'A.06', 'Beton bertulang K-225 (cor, besi & bekisting)', 'm3', 'Pekerjaan Struktur', 13),
  ('an-a-07', 'A.07', 'Pasangan dinding bata ringan', 'm2', 'Pekerjaan Arsitektur', 13),
  ('an-a-08', 'A.08', 'Plesteran & acian dinding', 'm2', 'Pekerjaan Arsitektur', 13),
  ('an-a-09', 'A.09', 'Pasang keramik lantai 40×40', 'm2', 'Pekerjaan Arsitektur', 13),
  ('an-a-10', 'A.10', 'Pengecatan tembok interior', 'm2', 'Pekerjaan Arsitektur', 13),
  ('an-a-11', 'A.11', 'Instalasi titik listrik', 'titik', 'Pekerjaan MEP', 13),
  ('an-a-12', 'A.12', 'Pemasangan pipa air bersih PVC 1/2"', 'm''', 'Pekerjaan MEP', 13)
on conflict ("id") do nothing;

-- 64 komponen analisa.
insert into proyek.komponen_analisa ("id", "analisaId", "hargaDasarId", "koefisien", "urutan") values
  ('ka-a-01-01', 'an-a-01', 'hd-l-01', 0.1, 0),
  ('ka-a-01-02', 'an-a-01', 'hd-l-06', 0.005, 1),
  ('ka-a-02-01', 'an-a-02', 'hd-l-01', 0.1, 0),
  ('ka-a-02-02', 'an-a-02', 'hd-l-03', 0.1, 1),
  ('ka-a-02-03', 'an-a-02', 'hd-l-05', 0.01, 2),
  ('ka-a-02-04', 'an-a-02', 'hd-l-06', 0.005, 3),
  ('ka-a-02-05', 'an-a-02', 'hd-m-08', 0.012, 4),
  ('ka-a-02-06', 'an-a-02', 'hd-m-09', 0.02, 5),
  ('ka-a-03-01', 'an-a-03', 'hd-l-01', 0.75, 0),
  ('ka-a-03-02', 'an-a-03', 'hd-l-06', 0.025, 1),
  ('ka-a-04-01', 'an-a-04', 'hd-l-01', 0.25, 0),
  ('ka-a-04-02', 'an-a-04', 'hd-l-06', 0.008, 1),
  ('ka-a-05-01', 'an-a-05', 'hd-m-04', 1.2, 0),
  ('ka-a-05-02', 'an-a-05', 'hd-m-01', 163, 1),
  ('ka-a-05-03', 'an-a-05', 'hd-m-02', 0.52, 2),
  ('ka-a-05-04', 'an-a-05', 'hd-l-01', 1.5, 3),
  ('ka-a-05-05', 'an-a-05', 'hd-l-02', 0.75, 4),
  ('ka-a-05-06', 'an-a-05', 'hd-l-05', 0.075, 5),
  ('ka-a-05-07', 'an-a-05', 'hd-l-06', 0.075, 6),
  ('ka-a-06-01', 'an-a-06', 'hd-m-01', 371, 0),
  ('ka-a-06-02', 'an-a-06', 'hd-m-03', 0.499, 1),
  ('ka-a-06-03', 'an-a-06', 'hd-m-05', 0.776, 2),
  ('ka-a-06-04', 'an-a-06', 'hd-m-06', 105, 3),
  ('ka-a-06-05', 'an-a-06', 'hd-m-07', 1.5, 4),
  ('ka-a-06-06', 'an-a-06', 'hd-m-08', 0.04, 5),
  ('ka-a-06-07', 'an-a-06', 'hd-m-09', 0.4, 6),
  ('ka-a-06-08', 'an-a-06', 'hd-l-01', 5.3, 7),
  ('ka-a-06-09', 'an-a-06', 'hd-l-02', 1, 8),
  ('ka-a-06-10', 'an-a-06', 'hd-l-05', 0.1, 9),
  ('ka-a-06-11', 'an-a-06', 'hd-l-06', 0.265, 10),
  ('ka-a-06-12', 'an-a-06', 'hd-e-01', 0.1, 11),
  ('ka-a-07-01', 'an-a-07', 'hd-m-10', 0.1, 0),
  ('ka-a-07-02', 'an-a-07', 'hd-m-11', 0.12, 1),
  ('ka-a-07-03', 'an-a-07', 'hd-l-01', 0.3, 2),
  ('ka-a-07-04', 'an-a-07', 'hd-l-02', 0.15, 3),
  ('ka-a-07-05', 'an-a-07', 'hd-l-05', 0.015, 4),
  ('ka-a-07-06', 'an-a-07', 'hd-l-06', 0.015, 5),
  ('ka-a-08-01', 'an-a-08', 'hd-m-11', 0.2, 0),
  ('ka-a-08-02', 'an-a-08', 'hd-l-01', 0.3, 1),
  ('ka-a-08-03', 'an-a-08', 'hd-l-02', 0.15, 2),
  ('ka-a-08-04', 'an-a-08', 'hd-l-05', 0.015, 3),
  ('ka-a-08-05', 'an-a-08', 'hd-l-06', 0.015, 4),
  ('ka-a-09-01', 'an-a-09', 'hd-m-12', 1.05, 0),
  ('ka-a-09-02', 'an-a-09', 'hd-m-11', 0.1, 1),
  ('ka-a-09-03', 'an-a-09', 'hd-l-01', 0.35, 2),
  ('ka-a-09-04', 'an-a-09', 'hd-l-02', 0.175, 3),
  ('ka-a-09-05', 'an-a-09', 'hd-l-05', 0.018, 4),
  ('ka-a-09-06', 'an-a-09', 'hd-l-06', 0.018, 5),
  ('ka-a-10-01', 'an-a-10', 'hd-m-13', 0.26, 0),
  ('ka-a-10-02', 'an-a-10', 'hd-l-01', 0.02, 1),
  ('ka-a-10-03', 'an-a-10', 'hd-l-02', 0.063, 2),
  ('ka-a-10-04', 'an-a-10', 'hd-l-05', 0.006, 3),
  ('ka-a-10-05', 'an-a-10', 'hd-l-06', 0.003, 4),
  ('ka-a-11-01', 'an-a-11', 'hd-m-15', 12, 0),
  ('ka-a-11-02', 'an-a-11', 'hd-m-16', 1, 1),
  ('ka-a-11-03', 'an-a-11', 'hd-l-01', 0.4, 2),
  ('ka-a-11-04', 'an-a-11', 'hd-l-02', 0.4, 3),
  ('ka-a-11-05', 'an-a-11', 'hd-l-05', 0.04, 4),
  ('ka-a-11-06', 'an-a-11', 'hd-l-06', 0.02, 5),
  ('ka-a-12-01', 'an-a-12', 'hd-m-14', 0.3, 0),
  ('ka-a-12-02', 'an-a-12', 'hd-l-01', 0.036, 1),
  ('ka-a-12-03', 'an-a-12', 'hd-l-02', 0.06, 2),
  ('ka-a-12-04', 'an-a-12', 'hd-l-05', 0.006, 3),
  ('ka-a-12-05', 'an-a-12', 'hd-l-06', 0.003, 4)
on conflict ("id") do nothing;

commit;
